### ISSUE TITLE
配合layouts使用，就会报错

### ISSUE THREAD

**Issue by yongchin0821** [Siricee/Nuxt3-markdown-starter#1]
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/31945560/161886155-5e67798b-233c-4043-a6a2-e9b113293644.png">

这边添加了一个layouts。然后yarn dev启动，就会报错Uncaught (in promise) Error: Module "fs" has been externalized for browser compatibility and cannot be accessed in client code.

有解决办法吗？
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/31945560/161886287-dcb9b9a2-169f-4121-b594-e322401cabab.png">

**Comment by Siricee** [comment]
我没遇到这个问题，我设置layouts之后没有遇到你这个error。

但 Nuxt3 目前对路由和静态站的支持性似乎并不完全，看起来还有好多没完成的功能…我写这个starter仅仅是让nuxt3读取markdown生成页面而已，连build都不能成功…
